package gnucash.entity

data class Customer(
    override var guid: String,
    var name: String,
    var id: String,
    var notes: String,
    var active: Int,
    var discountNum: Long,
    var discountDenom: Long,
    var creditNum: Long,
    var creditDenom: Long,
    var currency: String,
    var taxOverride: Int,
    var addrName: String?,
    var addrAddr1: String?,
    var addrAddr2: String?,
    var addrAddr3: String?,
    var addrAddr4: String?,
    var addrPhone: String?,
    var addrFax: String?,
    var addrEmail: String?,
    var shipaddrName: String?,
    var shipaddrAddr1: String?,
    var shipaddrAddr2: String?,
    var shipaddrAddr3: String?,
    var shipaddrAddr4: String?,
    var shipaddrPhone: String?,
    var shipaddrFax: String?,
    var shipaddrEmail: String?,
    var terms: String?,
    var taxIncluded: Int?,
    var taxtable: String?
) : Entity