package gnucash.entity

data class Entry(
    override var guid: String,
    var date: String,
    var dateEntered: String?,
    var description: String?,
    var action: String?,
    var notes: String?,
    var quantityNum: Long?,
    var quantityDenom: Long?,
    var iAcct: String?,
    var iPriceNum: Long?,
    var iPriceDenom: Long?,
    var iDiscountNum: Long?,
    var iDiscountDenom: Long?,
    var invoice: String?,
    var iDiscType: String?,
    var iDiscHow: String?,
    var iTaxable: Int?,
    var iTaxincluded: Int?,
    var iTaxtable: String?,
    var bAcct: String?,
    var bPriceNum: Long?,
    var bPriceDenom: Long?,
    var bill: String?,
    var bTaxable: Int?,
    var bTaxincluded: Int?,
    var bTaxtable: String?,
    var bPaytype: Int?,
    var billable: Int?,
    var billtoType: Int?,
    var billtoGuid: String?,
    var orderGuid: String?
) : Entity